name: Terraform OIDC Deploy

on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest

    outputs:
      environment: ${{ steps.env.outputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "environment=qa" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::645387694777:role/terraform-oidc-iam-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=env/${{ steps.env.outputs.environment }}.tfvars

  apply:
    needs: plan

    runs-on: ubuntu-latest

    environment:
      name: ${{ needs.plan.outputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::645387694777:role/terraform-oidc-iam-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=env/${{ needs.plan.outputs.environment }}.tfvars